# 1. New Database Connection (Updated for smart_finance_db_uetf)
spring.datasource.url=jdbc:postgresql://dpg-d7mr2b8g4nts73aqb1t0-a.singapore-postgres.render.com/smart_finance_db_uetf
spring.datasource.username=harsh_admin
spring.datasource.password=l6H27W4RudfAI9JJhuthzwIhViqSkNlG
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate/JPA Settings
# 'update' ???? ???? ???????????? ???? ????? ???? ????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Render Port Configuration
server.port=${PORT:8080}

# 4. Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000