# ?. ??????? ??????? (SSL ?????)
spring.datasource.url=jdbc:postgresql://dpg-d7mr2b8g4nts73aqb1t0-a.singapore-postgres.render.com/smart_finance_db_uetf?sslmode=require
spring.datasource.username=harsh_admin
spring.datasource.password=l6H27W4RudfAI9JJhuthzwIhViqSkNlG
spring.datasource.driver-class-name=org.postgresql.Driver

# ?. JPA / Hibernate ???????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# ???: ???? Spring Boot ??????????? ????? ???????? ?????? ????? ?????? ????
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ?. Hikari Connection Pool (Render ???? ???? ????????? ?? ??????????? ???)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# ?. ??????? ?????
server.port=${PORT:8080}